### ISSUE TITLE
lint: add new lint rule to enforce version is pinned in `package.name` (if `package.version` specified)

### ISSUE THREAD

**Issue by Dentrax** [wolfi-dev/wolfictl#215]
**Description**

Imagine we want to build the following package:

```yaml
package:
  name: foo
  version: 1.2.3
```

We should not allow this since there could be already package named `foo` that use the `latest`. Instead it'd be nice to pass if `-major.minor` is set as suffix.

Valid:

```yaml
package:
  name: foo-1
  version: 1.2.3
```

```yaml
package:
  name: foo-1.2
  version: 1.2.3
```

```yaml
package:
  name: foo-1.2.3
  version: 1.2.3
```

Not valid: (Version mismatch)

```yaml
package:
  name: foo-2.1
  version: 1.2.3
```
